services:
  backend-app:
    build: backend
    restart: always
    container_name: fogcast-api
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://fogcast-api:8000/health-check || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - INFLUXDB_URL=http://fogcast-influxdb:8086
      - INFLUXDB_TOKEN=YfT61spkrdsg5LLmsG9Nkx3gbzb0NMRxGqn1ELk4OccnYjJ0R1qG8iFcny3nPCobYHCQd3GHbaMl0pv55hn8vw==
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
